### ISSUE TITLE
usps_international bug when a service is passed via the SDK

### ISSUE THREAD

**Issue by nahall** [karrioapi/karrio#257]
Using the SDK, create a RateRequest with services filled in and have it go to the usps_international gateway. Error is generated:

```
Traceback (most recent call last):
  File "karrio/sdk/core/karrio/api/interface.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "karrio/sdk/core/karrio/api/interface.py", line 296, in process
    request: lib.Serializable = gateway.mapper.create_rate_request(payload)
  File "karrio/sdk/extensions/usps_international/karrio/mappers/usps_international/mapper.py", line 46, in create_rate_request
    return rate_request(payload, self.settings)
  File "karrio/sdk/extensions/usps_international/karrio/providers/usps_international/rate.py", line 120, in rate_request
    if any(
  File "karrio/sdk/extensions/usps_international/karrio/providers/usps_international/rate.py", line 121, in <genexpr>
    "global_express_guaranteed" in s.name for s in payload.services
AttributeError: 'str' object has no attribute 'name'
```

**Comment by danh91** [comment]
I believe this was solved.

Please reopen if not
