### ISSUE TITLE
karrio.dashboard causing request throttling

### ISSUE THREAD

**Issue by MarcoWel** [karrioapi/karrio#309]
**Describe the bug**
Clicking through the karrio dashboard leads to frequent 500 errors.

**To Reproduce**
1. Set up a fresh karrio instance:
```bash
git clone --depth 1 https://github.com/karrioapi/karrio
cd karrio/docker
sudo docker-compose up
```
3. Log into the dashboard.
4. Keep clicking trough the menus until you encounter a 500 error.

**Expected behavior**
No 500 errors should be thrown.

**Screenshots**
![image](https://user-images.githubusercontent.com/80592577/219711403-650602c9-3d30-42a4-87ae-881c2ce33905.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Chrome, Firefox
 - Version: karrio 2023.1.5

**Additional context**
Logs:
```bash
karrio.api   | ERROR exceptions.py 49 Request was throttled. Expected available in 30 seconds.
karrio.api   | Traceback (most recent call last):
karrio.api   |   File "/karrio/venv/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
karrio.api   |     self.initial(request, *args, **kwargs)
karrio.api   |   File "/karrio/venv/lib/python3.10/site-packages/rest_framework/views.py", line 416, in initial
karrio.api   |     self.check_throttles(request)
karrio.api   |   File "/karrio/venv/lib/python3.10/site-packages/rest_framework/views.py", line 371, in check_throttles
karrio.api   |     self.throttled(request, duration)
karrio.api   |   File "/karrio/venv/lib/python3.10/site-packages/rest_framework/views.py", line 181, in throttled
karrio.api   |     raise exceptions.Throttled(wait)
karrio.api   | rest_framework.exceptions.Throttled: Request was throttled. Expected available in 30 seconds.
karrio.api   | WARNING log.py 241 Too Many Requests: /
karrio.dashboard | {"level":50,"time":1676624051233,"env":"production","msg":"Failed to fetch API metadata from (http://api:5002)"}
karrio.dashboard | {"level":50,"time":1676624051233,"env":"production","errors":[{"code":"throttled","message":"Request was throttled. Expected available in 30 seconds."}]} 
```

Fix: The issue seems to be in `server/main/karrio/server/settings/base.py`:
`"DEFAULT_THROTTLE_RATES": {"anon": "40/minute", "user": "60/minute"},`

**Comment by danh91** [comment]
Thanks much @MarcoWel
