### ISSUE TITLE
DPDHL: Improve error display for label creation

### ISSUE THREAD

**Issue by MarcoWel** [karrioapi/karrio#368]
**Describe the bug**
When there is an error during DPDHL label creation, Karrio dashboard shows a very generic error message. There is no error shown in the Karrio request logs in the dashboard, only in the Karrio docker logs.

**To Reproduce**
1. Create a DPDHL service with correct credentials, but wrong account number
2. Try creating a shipment in Karrio dashboard.
3. Check the displayed error and logs.

**Expected behavior**
The error message displayed during label creation should contain relevant info. The extended error info should be available in the Karrio logs in the dashboard.

**Screenshots**
![image](https://user-images.githubusercontent.com/80592577/233791477-36ef2c17-da76-4a8d-a654-a043280be2bc.png)

**Desktop (please complete the following information):**
 - Version 2023.04.1.01

**Additional context**
Error shown in karrio docker logs:

```
karrio.api        | karrio.server.core.exceptions.APIException: [
Message(carrier_name='dpdhl', carrier_id='DHL', message='Hard validation error occured.', code=1101, details={}),
Message(carrier_name='dpdhl', carrier_id='DHL', message='Hard validation error occured.', code=1101, details={
'message': 'Die ausgewählte Abrechnungsnummer ist nicht gültig. Die angegebene Straße kann nicht gefunden werden.
Der eingegebene Wert ist zu lang und wurde gekürzt. Die ausgewählte Abrechnungsnummer ist nicht gültig.', 'error': '  \n
ShipmentOrder.Shipment.ShipmentDetails.cis:accountNumber\n            : Die ausgewählte Abrechnungsnummer ist nicht gültig.',
'warning': [<dpdhl_lib.business_interface.StatusElement object at 0x7f1b77d9ff10>, <dpdhl_lib.business_interface.StatusElement object at 0x7f1b77d9c310>]})]
karrio.api        | 
karrio.api        | During handling of the above exception, another exception occurred:
karrio.api        | 
karrio.api        | Traceback (most recent call last):
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/asgiref/sync.py", line 486, in thread_handler
karrio.api        |     raise exc_info[1]
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
karrio.api        |     response = await get_response(request)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
karrio.api        |     response = await wrapped_callback(
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/asgiref/sync.py", line 448, in __call__
karrio.api        |     ret = await asyncio.wait_for(future, timeout=None)
karrio.api        |   File "/usr/local/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
karrio.api        |     return await fut
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 22, in run
karrio.api        |     result = self.fn(*self.args, **self.kwargs)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/asgiref/sync.py", line 490, in thread_handler
karrio.api        |     return func(*args, **kwargs)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
karrio.api        |     return view_func(*args, **kwargs)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
karrio.api        |     return self.dispatch(request, *args, **kwargs)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
karrio.api        |     response = self.handle_exception(exc)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/rest_framework_tracking/base_mixins.py", line 48, in handle_exception
karrio.api        |     response = super(BaseLoggingMixin, self).handle_exception(exc)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/rest_framework/views.py", line 466, in handle_exception
karrio.api        |     response = exception_handler(exc, context)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/karrio/server/core/exceptions.py", line 53, in custom_exception_handler
karrio.api        |     messages = message_handler(exc)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/karrio/server/core/exceptions.py", line 140, in message_handler
karrio.api        |     messages=lib.to_dict(
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/karrio/lib.py", line 249, in to_dict
karrio.api        |     return utils.DP.to_dict(value, clear_empty=clear_empty)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/karrio/core/utils/dict.py", line 55, in to_dict
karrio.api        |     DICTPARSE.jsonify(entity)
karrio.api        |   File "/karrio/venv/lib/python3.10/site-packages/karrio/core/utils/dict.py", line 38, in jsonify
karrio.api        |     return json.dumps(
karrio.api        |   File "/usr/local/lib/python3.10/json/__init__.py", line 238, in dumps
karrio.api        |     **kw).encode(obj)
karrio.api        |   File "/usr/local/lib/python3.10/json/encoder.py", line 201, in encode
karrio.api        |     chunks = list(chunks)
karrio.api        |   File "/usr/local/lib/python3.10/json/encoder.py", line 429, in _iterencode
karrio.api        |     yield from _iterencode_list(o, _current_indent_level)
karrio.api        |   File "/usr/local/lib/python3.10/json/encoder.py", line 325, in _iterencode_list
karrio.api        |     yield from chunks
karrio.api        |   File "/usr/local/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
karrio.api        |     yield from chunks
karrio.api        |   File "/usr/local/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
karrio.api        |     yield from chunks
karrio.api        |   File "/usr/local/lib/python3.10/json/encoder.py", line 325, in _iterencode_list
karrio.api        |     yield from chunks
karrio.api        |   File "/usr/local/lib/python3.10/json/encoder.py", line 439, in _iterencode
karrio.api        |     yield from _iterencode(o, _current_indent_level)
karrio.api        |   File "/usr/local/lib/python3.10/json/encoder.py", line 431, in _iterencode
karrio.api        |     yield from _iterencode_dict(o, _current_indent_level)
karrio.api        |   File "/usr/local/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
karrio.api        |     yield from chunks
karrio.api        |   File "/usr/local/lib/python3.10/json/encoder.py", line 439, in _iterencode
karrio.api        |     yield from _iterencode(o, _current_indent_level)
karrio.api        |   File "/usr/local/lib/python3.10/json/encoder.py", line 436, in _iterencode
karrio.api        |     raise ValueError("Circular reference detected")
karrio.api        | ValueError: Circular reference detected

```

**Comment by danh91** [comment]
Looks like it is specific to DPDHL error parsing. Some unserializable XML objects in the details.

Could you please rename the issue to specifically DPDHL? Thanks

**Comment by danh91** [comment]
Fixed in https://github.com/karrioapi/karrio/pull/369

**Comment by MarcoWel** [comment]
Tested with 2023.4.4.01. It is improved but still lacking important information for dpdhl.
JSON field `details.message` should be included in the shown error.

karrio displays:
```
dpdhl Hard validation error occured.
dpdhl Hard validation error occured.
```

dpdhl response:
```json
{
  "messages": [
    {
      "carrier_id": "DHL",
      "carrier_name": "dpdhl",
      "code": 1101,
      "details": {},
      "message": "Hard validation error occured."
    },
    {
      "carrier_id": "DHL",
      "carrier_name": "dpdhl",
      "code": 1101,
      "details": {
        "error": "address.receiver.errorProp: Die eingegebene Adresse ist nicht leitcodierbar. \n                ShipmentOrder.Shipment.Packstation.cis:packstationNumber\n            : Bitte geben Sie eine Hausnummer an. \n                ShipmentOrder.Shipment.Packstation.cis:packstationNumber\n            : Packstationsnummern liegen zwischen 101 und 999. Bitte setzen Sie sich mit dem Empfänger in                   Verbindung, um eine korrekte Nummer zu erfragen.",
        "message": "Bitte geben Sie eine Hausnummer an. Die eingegebene Adresse ist nicht leitcodierbar. Bitte geben Sie eine Hausnummer an. Packstationsnummern liegen zwischen 101 und 999. Bitte setzen Sie sich mit dem Empfänger in                   Verbindung, um eine korrekte Nummer zu erfragen."
      },
      "message": "Hard validation error occured."
    }
  ]
}

```
