### ISSUE TITLE
UPS - Merchandise Description Required

### ISSUE THREAD

**Issue by StarTakko** [karrioapi/karrio#622]
**Describe the bug**
Merchandise Description is not added to the interface

**To Reproduce**
1.- Create shipping Mexico to Mexico with UPS
2.- Error "ups A package in a Mexico shipment must have a Merchandise Description."

Log api
```
INFO helpers.py 185 Request URL:: https://onlinetools.ups.com/api/rating/v2205/Shop?additionalinfo=timeintransit
INFO utils.py 73 successfully saved tracing records...
INFO helpers.py 185 Request URL:: https://onlinetools.ups.com/api/shipments/v2205/ship
ERROR helpers.py 219 HTTP Error 400: Bad Request
ERROR abstract.py 199 [Message(carrier_name='ups', carrier_id='ups', message='A package in a Mexico shipment must have a Merchandise Description.', code='121984', details=None)]
Traceback (most recent call last):
  File "/karrio/venv/lib/python3.11/site-packages/karrio/server/serializers/abstract.py", line 196, in create
    instance = super().create(payload, context=self.__context)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/karrio/venv/lib/python3.11/site-packages/karrio/server/manager/serializers/shipment.py", line 366, in create
    return gateway.Shipments.create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/karrio/venv/lib/python3.11/site-packages/karrio/server/core/gateway.py", line 206, in create
    raise exceptions.APIException(
karrio.server.core.exceptions.APIException: [Message(carrier_name='ups', carrier_id='ups', message='A package in a Mexico shipment must have a Merchandise Description.', code='121984', details=None)]
ERROR exceptions.py 49 [Message(carrier_name='ups', carrier_id='ups', message='A package in a Mexico shipment must have a Merchandise Description.', code='121984', details=None)]
Traceback (most recent call last):
  File "/karrio/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/karrio/venv/lib/python3.11/site-packages/karrio/server/manager/views/shipments.py", line 245, in post
    update = buy_shipment_label(
             ^^^^^^^^^^^^^^^^^^^
  File "/karrio/venv/lib/python3.11/site-packages/karrio/server/manager/serializers/shipment.py", line 505, in buy_shipment_label
    .save(carrier=carrier)
     ^^^^^^^^^^^^^^^^^^^^^
  File "/karrio/venv/lib/python3.11/site-packages/karrio/server/serializers/abstract.py", line 46, in save
    self._instance = self._serializer.save(**kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/karrio/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/karrio/venv/lib/python3.11/site-packages/karrio/server/serializers/abstract.py", line 200, in create
    raise e
  File "/karrio/venv/lib/python3.11/site-packages/karrio/server/serializers/abstract.py", line 196, in create
    instance = super().create(payload, context=self.__context)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/karrio/venv/lib/python3.11/site-packages/karrio/server/manager/serializers/shipment.py", line 366, in create
    return gateway.Shipments.create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/karrio/venv/lib/python3.11/site-packages/karrio/server/core/gateway.py", line 206, in create
    raise exceptions.APIException(
karrio.server.core.exceptions.APIException: [Message(carrier_name='ups', carrier_id='ups', message='A package in a Mexico shipment must have a Merchandise Description.', code='121984', details=None)]
WARNING log.py 241 Failed Dependency: /v1/shipments/shp_29bd74fe70e1448f8b361220930178ef/purchase
INFO utils.py 73 successfully saved tracing records...
```

**Comment by StarTakko** [comment]
Request Timeline

```
{
  "ShipmentRequest": {
    "LabelSpecification": {
      "LabelImageFormat": {
        "Code": "PNG",
        "Description": "lable format"
      },
      "LabelStockSize": {
        "Height": "6",
        "Width": "4"
      }
    },
    "Request": {
      "RequestOption": "validate",
      "SubVersion": "v2205",
      "TransactionReference": {
        "CustomerContext": "generate label"
      }
    },
    "Shipment": {
      "Description": "Prueba",
      "InvoiceLineTotal": {
        "CurrencyCode": "USD",
        "MonetaryValue": "10.0"
      },
      "NumOfPiecesInShipment": "1",
      "Package": [
        {
          "Dimensions": {
            "Height": "18.2",
            "Length": "10.0",
            "UnitOfMeasurement": {
              "Code": "CM",
              "Description": "Dimension"
            },
            "Width": "33.7"
          },
          "PackageWeight": {
            "UnitOfMeasurement": {
              "Code": "KGS",
              "Description": "Weight"
            },
            "Weight": "1.0"
          },
          "Packaging": {
            "Code": "02",
            "Description": "Packaging Type"
          }
        }
      ],
      "PaymentInformation": {
        "ShipmentCharge": [
          {
            "BillShipper": {
              "AccountNumber": "XXXXX"
            },
            "Type": "01"
          },
          {
            "BillShipper": {
              "AccountNumber": "XXXXX"
            },
            "Type": "02"
          }
        ]
      },
      "RatingMethodRequestedIndicator": "Y",
      "Service": {
        "Code": "11",
        "Description": "ups_standard"
      },
      "ShipFrom": {
        "Address": {
          "AddressLine": "XXXXXXX",
          "City": "Mexicali",
          "CountryCode": "MX",
          "PostalCode": "21290",
          "StateProvinceCode": "B.C."
        },
        "AttentionName": "Esteban XXXXX",
        "Name": "Esteban XXXXX",
        "Phone": {
          "Number": "000-000-0000"
        }
      },
      "ShipTo": {
        "Address": {
          "AddressLine": "XXXXXXXXX",
          "City": "León de los Aldama",
          "CountryCode": "MX",
          "PostalCode": "37208",
          "StateProvinceCode": "GT"
        },
        "AttentionName": "XXXX",
        "Name": "XXXXX",
        "Phone": {
          "Number": "000-000-0000"
        }
      },
      "ShipmentRatingOptions": {
        "NegotiatedRatesIndicator": "Y"
      },
      "ShipmentServiceOptions": {},
      "Shipper": {
        "Address": {
          "AddressLine": "XXXXX",
          "City": "Mexicali",
          "CountryCode": "MX",
          "PostalCode": "21290",
          "StateProvinceCode": "B.C."
        },
        "AttentionName": "Esteban XXXX",
        "Name": "Esteban XXXX",
        "Phone": {
          "Number": "000-000-0000"
        },
        "ShipperNumber": "XXXX"
      },
      "TaxInformationIndicator": "Y"
    }
  }
}
``` 

Response body

```
{  "messages": [    {      "carrier_id": "ups",      "carrier_name": "ups",      "code": "121984",      "message": "A package in a Mexico shipment must have a Merchandise Description."    }  ]}
```
