### ISSUE TITLE
Migrations from 2024.2.12 to 2024.6-rc25 fails due to pending trigger events

### ISSUE THREAD

**Issue by DarkSwoop** [karrioapi/karrio#645]
When attempting to migrate the karrio server to the new release candidate, the migrations fail like shown below. I ran this locally, imported a dump of our live db and tried to start karrio with docker compose using the docker/docker-compose.yml file.

Current live version: 2024.2.12
Trying to migrate to: 2024.6-rc25

There seems to be something running in the background that prevents the creation of the index.

Log:

```
karrio.api        | Redis connection initialized at: redis://redis:6379/1
karrio.api        | Operations to perform:
karrio.api        |   Apply all migrations: admin, apps, auth, constance, contenttypes, core, data, db, documents, events, graph, iam, manager, oauth2_provider, orders, otp_email, otp_static, otp_totp, pricing, providers, rest_framework_tracking, sessions, tracing, two_factor, user
karrio.api        | Running migrations:
karrio.api        |   Applying documents.0007_alter_documenttemplate_related_object... OK
karrio.api        |   Applying manager.0059_shipment_return_address... OK
karrio.api        |   Applying oauth2_provider.0008_alter_accesstoken_token... OK
karrio.api        |   Applying oauth2_provider.0009_add_hash_client_secret... OK
karrio.api        |   Applying oauth2_provider.0010_application_allowed_origins... OK
karrio.api        |   Applying otp_email.0006_add_timestamps... OK
karrio.api        |   Applying otp_static.0003_add_timestamps... OK
karrio.api        |   Applying otp_totp.0003_add_timestamps... OK
karrio.api        |   Applying pricing.0050_alter_surcharge_carriers... OK
karrio.api        |   Applying pricing.0051_alter_surcharge_carriers_alter_surcharge_services... OK
karrio.api        |   Applying pricing.0052_alter_surcharge_carriers_alter_surcharge_services... OK
karrio.api        |   Applying pricing.0053_alter_surcharge_carriers_alter_surcharge_services... OK
karrio.api        |   Applying pricing.0054_alter_surcharge_services... OK
karrio.api        |   Applying pricing.0055_alter_surcharge_services... OK
karrio.api        |   Applying pricing.0056_alter_surcharge_carriers_alter_surcharge_services... OK
karrio.api        |   Applying providers.0072_rename_eshippersettings_eshipperxmlsettings_and_more... OK
karrio.api        |   Applying providers.0073_delete_eshipperxmlsettings... OK
karrio.api        |   Applying providers.0074_eshippersettings... OK
karrio.api        |   Applying providers.0075_haypostsettings... OK
karrio.api        |   Applying providers.0076_rename_customer_registration_id_uspsinternationalsettings_account_number_and_more... OK
karrio.db         | 2024-08-13 12:47:20.601 UTC [98] ERROR:  cannot CREATE INDEX "providers_carrier" because it has pending trigger events
karrio.db         | 2024-08-13 12:47:20.601 UTC [98] STATEMENT:  CREATE INDEX "providers_carrier_carrier_code_c3dc782f" ON "providers_carrier" ("carrier_code")
karrio.api        | Traceback (most recent call last):
karrio.api        |   File "/karrio/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
karrio.api        |     return self.cursor.execute(sql)
karrio.api        |            ^^^^^^^^^^^^^^^^^^^^^^^^
karrio.api        | psycopg2.errors.ObjectInUse: cannot CREATE INDEX "providers_carrier" because it has pending trigger events
karrio.api        |
karrio.api        |
karrio.api        | The above exception was the direct cause of the following exception:
karrio.api        |
karrio.api        | Traceback (most recent call last):
karrio.api        |   File "/karrio/venv/bin/karrio", line 8, in <module>
karrio.api        |     sys.exit(main())
karrio.api        |              ^^^^^^
karrio.api        |   File "/karrio/venv/lib/python3.11/site-packages/karrio/server/__main__.py", line 17, in main
karrio.api        |     execute_from_command_line(sys.argv)
karrio.api        |   File "/karrio/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
karrio.api        |     utility.execute()
karrio.api        |   File "/karrio/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
karrio.api        |     self.fetch_command(subcommand).run_from_argv(self.argv)
karrio.api        |   File "/karrio/venv/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
karrio.api        |     self.execute(*args, **cmd_options)
karrio.api        |   File "/karrio/venv/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
karrio.api        |     output = self.handle(*args, **options)
karrio.api        |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
karrio.api        |   File "/karrio/venv/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
karrio.api        |     res = handle_func(*args, **kwargs)
karrio.api        |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
karrio.api        |   File "/karrio/venv/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 356, in handle
karrio.api        |     post_migrate_state = executor.migrate(
karrio.api        |                          ^^^^^^^^^^^^^^^^^
karrio.api        |   File "/karrio/venv/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
karrio.api        |     state = self._migrate_all_forwards(
karrio.api        |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
karrio.api        |   File "/karrio/venv/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
karrio.api        |     state = self.apply_migration(
karrio.api        |             ^^^^^^^^^^^^^^^^^^^^^
karrio.api        |   File "/karrio/venv/lib/python3.11/site-packages/django/db/migrations/executor.py", line 249, in apply_migration
karrio.api        |     with self.connection.schema_editor(
karrio.api        |   File "/karrio/venv/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 166, in __exit__
karrio.api        |     self.execute(sql)
karrio.api        |   File "/karrio/venv/lib/python3.11/site-packages/django/db/backends/postgresql/schema.py", line 48, in execute
karrio.api        |     return super().execute(sql, None)
karrio.api        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
karrio.api        |   File "/karrio/venv/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 201, in execute
karrio.api        |     cursor.execute(sql, params)
karrio.api        |   File "/karrio/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
karrio.api        |     return super().execute(sql, params)
karrio.api        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
karrio.api        |   File "/karrio/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
karrio.api        |     return self._execute_with_wrappers(
karrio.api        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
karrio.api        |   File "/karrio/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
karrio.api        |     return executor(sql, params, many, context)
karrio.api        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
karrio.api        |   File "/karrio/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
karrio.api        |     with self.db.wrap_database_errors:
karrio.api        |   File "/karrio/venv/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
karrio.api        |     raise dj_exc_value.with_traceback(traceback) from exc_value
karrio.api        |   File "/karrio/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
karrio.api        |     return self.cursor.execute(sql)
karrio.api        |            ^^^^^^^^^^^^^^^^^^^^^^^^
karrio.api        | django.db.utils.OperationalError: cannot CREATE INDEX "providers_carrier" because it has pending trigger events
```

**Comment by danh91** [comment]
Thanks, @DarkSwoop for the logs. I was able to reproduce and debug it.
Please, test `rc26`

**Comment by DarkSwoop** [comment]
Worked. Thanks! 💯
